after_script:
  - docker images

before_script:
  - IMAGE="postgres-plv8:$POSTGRES_VERSION-$PLV8"

env:
  - POSTGRES=9.5 POSTGRES_VERSION=9.5.2 PLV8=1.4.4


language: bash

script:
  - docker build -t "${IMAGE}" "${POSTGRES}"
  - docker run -d --name postgres "${IMAGE}"
  - sleep 3
  - while ! docker exec -it postgres pg_isready -U postgres -h 127.0.0.1; do echo "$(date) - waiting for database to start"; sleep 1; done
  - docker exec -it postgres psql -U postgres -c 'CREATE EXTENSION plv8; DO $$ plv8.elog(WARNING, plv8.version) $$ LANGUAGE plv8' | grep "${VERSION#????}"

services: docker
