version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4.1
  aws-ecr: circleci/aws-ecr@9.6.0

jobs:
  build-and-push-image:
    parameters:
      postgres_version:
        type: string
        default: "14.19"
      plv8_version:
        type: string
        default: "2.3.15"
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - aws-cli/setup
      # - aws-ecr/ecr_login
      # - run:
      #     command: |
      #       image_name = "postgres-plv8:<< parameters.postgres_version >>-<< parameters.plv8_version >>"
      #       ecr_repo = "unidays/docker-postgres-plv8"
      #       image_tag = "<< parameters.postgres_version >>-<< parameters.plv8_version >>"
      #       docker build -t $image_tag << parameters.postgres_version >>/<< parameters.plv8_version >>
      #       docker tag $image_tag $ecr_repo:$image_tag
      #       docker push $ecr_repo
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup
          create_repo: false
          dockerfile: Dockerfile
          no_output_timeout: 10m
          path: << parameters.postgres_version >>/<< parameters.plv8_version >>
          platform: linux/amd64
          public_registry: true
          public_registry_alias: unidays
          push_image: false
          region: us-east-1
          repo: unidays/docker-postgres-plv8
          repo_scan_on_push: true
          tag: "<< parameters.postgres_version >>-<< parameters.plv8_version >>"

workflows:
  build-images:
    jobs:
      - build-and-push-image:
          context: aws-cf-deployment-dev
          name: build-and-push-14-19--2-3-15
          postgres_version: "14.19"
          plv8_version: "2.3.15"
      - build-and-push-image:
          context: aws-cf-deployment-dev
          name: build-and-push-14-19--3-1-10
          postgres_version: "14.19"
          plv8_version: "3.1.10"
